from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(285, 380)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        MainWindow.setFont(font)
        MainWindow.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        # MainWindow.move(0, 0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # PARAMETERS

        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)

        self.w = QtGui.QLineEdit(self.centralwidget)
        self.w.setGeometry(QtCore.QRect(50, 10, 51, 21))
        self.w.setToolTip("Window size")
        self.w.setObjectName("w")
        self.wLabel = QtGui.QLabel(self.centralwidget)
        self.wLabel.setGeometry(QtCore.QRect(30, 10, 21, 16))
        self.wLabel.setFont(font)
        self.wLabel.setObjectName("wLabel")

        self.N = QtGui.QLineEdit(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.N.setToolTip("FFT size (minimum 512)")
        self.N.setObjectName("N")
        self.NLabel = QtGui.QLabel(self.centralwidget)
        self.NLabel.setGeometry(QtCore.QRect(110, 10, 21, 16))
        self.NLabel.setFont(font)
        self.NLabel.setObjectName("NLabel")

        self.t = QtGui.QLineEdit(self.centralwidget)
        self.t.setGeometry(QtCore.QRect(205, 10, 41, 21))
        self.t.setToolTip("Threshold in negative dB")
        self.t.setObjectName("t")
        self.tLabel = QtGui.QLabel(self.centralwidget)
        self.tLabel.setGeometry(QtCore.QRect(190, 10, 21, 16))
        self.tLabel.setFont(font)
        self.tLabel.setObjectName("tLabel")
       
        self.nH = QtGui.QLineEdit(self.centralwidget)
        self.nH.setGeometry(QtCore.QRect(40, 50, 31, 21))
        self.nH.setToolTip("Maximum number of harmonics")
        self.nH.setObjectName("nH")
        self.nHLabel = QtGui.QLabel(self.centralwidget)
        self.nHLabel.setGeometry(QtCore.QRect(10, 50, 21, 16))
        self.nHLabel.setFont(font)
        self.nHLabel.setObjectName("nHLabel")
        
        self.minf0 = QtGui.QLineEdit(self.centralwidget)
        self.minf0.setGeometry(QtCore.QRect(130, 50, 41, 21))
        self.minf0.setToolTip("Minimum f0 frequency in Hz")
        self.minf0.setObjectName("minf0")
        self.minf0Label = QtGui.QLabel(self.centralwidget)
        self.minf0Label.setGeometry(QtCore.QRect(80, 50, 51, 16))
        self.minf0Label.setFont(font)
        self.minf0Label.setObjectName("minf0Label")

        self.maxf0 = QtGui.QLineEdit(self.centralwidget)
        self.maxf0.setGeometry(QtCore.QRect(235, 50, 41, 21))
        self.maxf0.setToolTip("Maximum f0 frequency in Hz")
        self.maxf0.setObjectName("maxf0")
        self.maxf0Label = QtGui.QLabel(self.centralwidget)
        self.maxf0Label.setGeometry(QtCore.QRect(185, 50, 51, 16))
        self.maxf0Label.setFont(font)
        self.maxf0Label.setObjectName("maxf0Label")
        
        
        self.f0et = QtGui.QLineEdit(self.centralwidget)
        self.f0et.setGeometry(QtCore.QRect(55, 90, 31, 21))
        self.f0et.setToolTip("Error threshold in the f0 detection")
        self.f0et.setObjectName("f0et")
        self.f0etLabel = QtGui.QLabel(self.centralwidget)
        self.f0etLabel.setGeometry(QtCore.QRect(20, 90, 41, 16))
        self.f0etLabel.setFont(font)
        self.f0etLabel.setObjectName("f0etLabel")


        self.maxhd = QtGui.QLineEdit(self.centralwidget)
        self.maxhd.setGeometry(QtCore.QRect(150, 90, 31, 21))
        self.maxhd.setToolTip("Maximum relative deviation in harmonic detection")
        self.maxhd.setObjectName("maxhd")
        self.maxhdLabel = QtGui.QLabel(self.centralwidget)
        self.maxhdLabel.setGeometry(QtCore.QRect(95, 90, 61, 16))
        self.maxhdLabel.setFont(font)
        self.maxhdLabel.setObjectName("maxhdLabel")


        self.stocf = QtGui.QLineEdit(self.centralwidget)
        self.stocf.setGeometry(QtCore.QRect(235, 90, 31, 21))
        self.stocf.setToolTip("Decimation factor of mag. spectrum for stochastic analysis")
        self.stocf.setObjectName("stocf")
        self.stocfLabel = QtGui.QLabel(self.centralwidget)
        self.stocfLabel.setGeometry(QtCore.QRect(195, 90, 41, 16))
        self.stocfLabel.setFont(font)
        self.stocfLabel.setObjectName("stocfLabel")

        # SEPARATION
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 110, 285, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        
        # START IN FRAME NUMBER
        self.startinLabel = QtGui.QLabel(self.centralwidget)
        self.startinLabel.setGeometry(QtCore.QRect(10, 130, 151, 16))
        self.startinLabel.setObjectName("startinLabel")
        self.nFrameStart = QtGui.QLineEdit(self.centralwidget)
        self.nFrameStart.setGeometry(QtCore.QRect(160, 130, 51, 21))
        self.nFrameStart.setObjectName("nFrameStart")
        self.nFrameStart.setToolTip("Frame number to start plotting")
        
        # CONTROL BUTTONS  
        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setGeometry(QtCore.QRect(10, 160, 41, 32))
        self.pauseButton.setToolTip("Pause plots")
        self.pauseButton.setObjectName("pauseButton")
        self.nextButton = QtGui.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(55, 160, 41, 32))
        self.nextButton.setToolTip("Next plot")
        self.nextButton.setObjectName("nextButton")
        self.playButton = QtGui.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(100, 160, 41, 32))
        self.playButton.setToolTip("Play plots")
        self.playButton.setObjectName("playButton")
        self.rewindButton = QtGui.QPushButton(self.centralwidget)
        self.rewindButton.setGeometry(QtCore.QRect(145, 160, 41, 32))
        self.rewindButton.setToolTip("Rewind plots")
        self.rewindButton.setObjectName("rewindButton")
        self.doubleRewindButton = QtGui.QPushButton(self.centralwidget)
        self.doubleRewindButton.setGeometry(QtCore.QRect(190, 160, 41, 32))
        self.doubleRewindButton.setToolTip("Rewind plots faster")
        self.doubleRewindButton.setObjectName("doubleRewindButton")
        self.endButton = QtGui.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(235, 160, 41, 32))
        self.endButton.setToolTip("Go to the end without plotting")
        self.endButton.setObjectName("endButton")
        
        # SEPARATION 2

        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 195, 285, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        
        # PLAY OUTPUT
        self.xLabel = QtGui.QLabel(self.centralwidget)
        self.xLabel.setGeometry(QtCore.QRect(35, 225, 131, 16))
        self.xLabel.setObjectName("xLabel")
        self.yLabel = QtGui.QLabel(self.centralwidget)
        self.yLabel.setGeometry(QtCore.QRect(35, 265, 131, 16))
        self.yLabel.setObjectName("yLabel")
        self.yhLabel = QtGui.QLabel(self.centralwidget)
        self.yhLabel.setGeometry(QtCore.QRect(35, 305, 141, 16))
        self.yhLabel.setObjectName("yhLabel")
        self.ysLabel = QtGui.QLabel(self.centralwidget)
        self.ysLabel.setGeometry(QtCore.QRect(35, 345, 131, 16))
        self.ysLabel.setObjectName("ysLabel")

        self.playX = QtGui.QPushButton(self.centralwidget)
        self.playX.setEnabled(False)
        self.playX.setGeometry(QtCore.QRect(190, 215, 41, 32))
        self.playX.setToolTip("play sound")
        self.playX.setObjectName("playX")
        self.playY = QtGui.QPushButton(self.centralwidget)
        self.playY.setEnabled(False)
        self.playY.setGeometry(QtCore.QRect(190, 255, 41, 32))
        self.playY.setToolTip("play sound")
        self.playY.setObjectName("playY")
        self.playYh = QtGui.QPushButton(self.centralwidget)
        self.playYh.setEnabled(False)
        self.playYh.setGeometry(QtCore.QRect(190, 295, 41, 32))
        self.playYh.setToolTip("play sound")
        self.playYh.setObjectName("playYh")
        self.playYs = QtGui.QPushButton(self.centralwidget)
        self.playYs.setEnabled(False)
        self.playYs.setGeometry(QtCore.QRect(190, 335, 41, 32))
        self.playYs.setToolTip("play sound")
        self.playYs.setObjectName("playYs")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.w, self.N)
        MainWindow.setTabOrder(self.N, self.t)
        MainWindow.setTabOrder(self.t, self.nH)
        MainWindow.setTabOrder(self.nH, self.minf0)
        MainWindow.setTabOrder(self.minf0, self.maxf0)
        MainWindow.setTabOrder(self.maxf0, self.f0et)
        MainWindow.setTabOrder(self.f0et, self.maxhd)
        MainWindow.setTabOrder(self.maxhd, self.stocf)
        MainWindow.setTabOrder(self.stocf, self.nFrameStart)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        
        self.w.setText(QtGui.QApplication.translate("MainWindow", "801", None, QtGui.QApplication.UnicodeUTF8))
        self.wLabel.setText(QtGui.QApplication.translate("MainWindow", "w:", None, QtGui.QApplication.UnicodeUTF8))
        self.N.setText(QtGui.QApplication.translate("MainWindow", "1024", None, QtGui.QApplication.UnicodeUTF8))
        self.NLabel.setText(QtGui.QApplication.translate("MainWindow", "N:", None, QtGui.QApplication.UnicodeUTF8))
        self.t.setText(QtGui.QApplication.translate("MainWindow", "-60", None, QtGui.QApplication.UnicodeUTF8))
        self.tLabel.setText(QtGui.QApplication.translate("MainWindow", "t:", None, QtGui.QApplication.UnicodeUTF8))
        self.nH.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.nHLabel.setText(QtGui.QApplication.translate("MainWindow", "nH:", None, QtGui.QApplication.UnicodeUTF8))
        self.minf0.setText(QtGui.QApplication.translate("MainWindow", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.minf0Label.setText(QtGui.QApplication.translate("MainWindow", "minf0:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxf0.setText(QtGui.QApplication.translate("MainWindow", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.maxf0Label.setText(QtGui.QApplication.translate("MainWindow", "maxf0:", None, QtGui.QApplication.UnicodeUTF8))
        self.f0et.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.f0etLabel.setText(QtGui.QApplication.translate("MainWindow", "f0et:", None, QtGui.QApplication.UnicodeUTF8))
        self.maxhd.setText(QtGui.QApplication.translate("MainWindow", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.maxhdLabel.setText(QtGui.QApplication.translate("MainWindow", "maxhd:", None, QtGui.QApplication.UnicodeUTF8))
        self.stocf.setText(QtGui.QApplication.translate("MainWindow", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.stocfLabel.setText(QtGui.QApplication.translate("MainWindow", "stocf:", None, QtGui.QApplication.UnicodeUTF8))
        self.startinLabel.setText(QtGui.QApplication.translate("MainWindow", "Start in frame number:", None, QtGui.QApplication.UnicodeUTF8))
        self.nFrameStart.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))

        self.pauseButton.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "|>", None, QtGui.QApplication.UnicodeUTF8))
        self.rewindButton.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleRewindButton.setText(QtGui.QApplication.translate("MainWindow", ">>>", None, QtGui.QApplication.UnicodeUTF8))
        self.endButton.setText(QtGui.QApplication.translate("MainWindow", ">>|", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabel.setText(QtGui.QApplication.translate("MainWindow", "Original Sound (x): ", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabel.setText(QtGui.QApplication.translate("MainWindow", "Output Sound (y): ", None, QtGui.QApplication.UnicodeUTF8))
        self.yhLabel.setText(QtGui.QApplication.translate("MainWindow", "Stochastic Sound (yh): ", None, QtGui.QApplication.UnicodeUTF8))
        self.ysLabel.setText(QtGui.QApplication.translate("MainWindow", "Residual Sound (ys): ", None, QtGui.QApplication.UnicodeUTF8))
        self.playX.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.playY.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.playYh.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.playYs.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))

        
